# Generated by Django 5.2.3 on 2026-01-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(blank=True, help_text='Name displayed publicly (e.g., on reviews).', max_length=50, null=True),
        ),
    ]
